### ISSUE TITLE
Mailbox Expired, TimeZone issue

### ISSUE THREAD

**Issue by ZoobiDoobi** [johnnymast/10min#4]
Whenever I try to open the mailbox, It gives me **Mailbox Expired**, even if I do **Retire mailbox** or **Reset time**, it keeps saying **Mailbox Expired**

**Comment by johnnymast** [comment]
Hmm interesting.

**Comment by johnnymast** [comment]
I have assigned you to this job.

**Comment by johnnymast** [comment]
This issue should be fixed now.
